name: Build Binaries

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.${{ matrix.os-suffix }}

    strategy:
      fail-fast: false
      matrix:
        os-suffix: ['04', 04-arm]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@4.2.2

      - name: Create Docker Image Output folder
        run: mkdir image-output

      - name: Build Docker Image
        run: docker build -t alpine-build .

      - name: Mount image to file system
        run: sudo ctr image mount alpine-build image-output

      - name: Upload build to GitHub Actions Artifacts
        uses: actions/upload-artifact@4.6.2
        with:
          name: ${{ matrix.os-suffix}}-build
          path: image-output/build/mysql-9.4.0/bld
          if-no-files-found: error
          compression-level: 9

      - name: Upload image output to GitHub Actions Artifacts
        uses: actions/upload-artifact@4.6.2
        with:
          name: ${{ matrix.os-suffix}}-image-output
          path: image-output
          if-no-files-found: error
          compression-level: 9
