name: Build Binaries

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os.version }}

    permissions:
      id-token: write
      contents: read
      attestations: write

    strategy:
      fail-fast: false
      matrix:
        os:
          - version: ubuntu-24.04
            arch: x86_64
          - version: ubuntu-24.04-arm
            arch: arm64
        mysql_version:
          - version: 9.4.0
            line: 9.4
          - version: 9.3.0
            line: 9.3
          - version: 9.2.0
            line: 9.2
          - version: 9.1.0
            line: 9.1
          - version: 9.0.1
            line: '9.0'
          - version: 8.4.6
            line: 8.4
          - version: 8.4.5
            line: 8.4
          - version: 8.4.4
            line: 8.4
          - version: 8.4.3
            line: 8.4
          - version: 8.4.2
            line: 8.4
          - version: 8.4.0
            line: 8.4
          - version: 8.3.0
            line: 8.3
          - version: 8.2.0
            line: 8.2
          - version: 8.1.0
            line: 8.1
          - version: 8.0.43
            line: '8.0'
          - version: 8.0.42
            line: '8.0'
          - version: 8.0.41
            line: '8.0'
          - version: 8.0.40
            line: '8.0'
          - version: 8.0.39
            line: '8.0'
          - version: 8.0.37
            line: '8.0'
          - version: 8.0.36
            line: '8.0'
          - version: 8.0.35
            line: '8.0'
          - version: 8.0.34
            line: '8.0'
          - version: 8.0.33
            line: '8.0'
          - version: 8.0.32
            line: '8.0'
          - version: 8.0.31
            line: '8.0'
          - version: 8.0.30
            line: '8.0'
          - version: 8.0.28
            line: '8.0'
          - version: 8.0.27
            line: '8.0'
          - version: 8.0.26
            line: '8.0'
          - version: 8.0.25
            line: '8.0'
          - version: 8.0.24
            line: '8.0'
          - version: 8.0.23
            line: '8.0'
          - version: 8.0.22
            line: '8.0'
          - version: 8.0.21
            line: '8.0'
          - version: 8.0.20
            line: '8.0'
          - version: 8.0.19
            line: '8.0'
          - version: 8.0.18
            line: '8.0'
          - version: 8.0.17
            line: '8.0'
          - version: 8.0.16
            line: '8.0'
          - version: 8.0.15
            line: '8.0'
          - version: 8.0.14
            line: '8.0'
          - version: 8.0.13
            line: '8.0'
          - version: 8.0.12
            line: '8.0'
          - version: 8.0.11
            line: '8.0'
          - version: 8.0.4
            line: '8.0'
            release_type: -rc
          - version: 8.0.3
            line: '8.0'
            release_type: -rc
          - version: 8.0.2
            line: '8.0'
            release_type: -dmr
          - version: 8.0.1
            line: '8.0'
            release_type: -dmr
          - version: 8.0.0
            line: '8.0'
            release_type: -dmr
          - version: 5.7.44
            line: 5.7
          - version: 5.7.43
            line: 5.7
          - version: 5.7.42
            line: 5.7
          - version: 5.7.41
            line: 5.7
          - version: 5.7.40
            line: 5.7
          - version: 5.7.39
            line: 5.7
          - version: 5.7.38
            line: 5.7
          - version: 5.7.37
            line: 5.7
          - version: 5.7.36
            line: 5.7
          - version: 5.7.35
            line: 5.7
          - version: 5.7.34
            line: 5.7
          - version: 5.7.33
            line: 5.7
          - version: 5.7.32
            line: 5.7
          - version: 5.7.31
            line: 5.7
          - version: 5.7.30
            line: 5.7
          - version: 5.7.29
            line: 5.7
          - version: 5.7.28
            line: 5.7
          - version: 5.7.27
            line: 5.7
          - version: 5.7.26
            line: 5.7
          - version: 5.7.25
            line: 5.7
          - version: 5.7.24
            line: 5.7
          - version: 5.7.23
            line: 5.7
          - version: 5.7.22
            line: 5.7
          - version: 5.7.21
            line: 5.7
          - version: 5.7.20
            line: 5.7
          - version: 5.7.19
            line: 5.7

    steps:
      - name: Checkout Repository
        uses: actions/checkout@4.2.2

      - name: Build Docker Image
        run: docker build -t alpine-build --build-arg major_minor_version=${{ matrix.mysql_version.line }} --build-arg mysql_version=${{ matrix.mysql_version.version }} --build-arg url=$(echo $(if [[ ${{ matrix.mysql_version.version }} == "8.0.43" || ${{ matrix.mysql_version.version }} == "8.4.6" || ${{ matrix.mysql_version.version }} == "9.4.0" ]]; then echo "https://cdn.mysql.com/Downloads/MySQL-"; else echo "https://cdn.mysql.com/archives/mysql-"; fi)${{ matrix.mysql_version.line }}/mysql-${{ matrix.mysql_version.version }}${{ matrix.mysql_version.release_type }}.tar.gz) .

      - name: Export image contents
        run: docker export $(docker create alpine-build) -o image-output.tar

      - name: Upload export to GitHub Actions Artifacts
        uses: actions/upload-artifact@4.6.2
        with:
          name: ${{ matrix.os.arch }}-${{ matrix.mysql_version.version }}-image-output-tar
          path: image-output.tar
          if-no-files-found: error
          compression-level: 9

      - name: Untar image contents
        run: tar -xvf image-output.tar

      - name: Create build output folder
        run: mkdir build-output

      - name: List directory
        run: ls mysql-build

      - name: Copy license and README into the mysql build folder
        run: cp mysql-build/mysql-${{ matrix.mysql_version.version }}/{LICENSE,README} mysql-build/mysql-${{ matrix.mysql_version.version }}/mysql

      - name: Extract important files and folders from the mysql build folder into build output folder
        run: cp -r mysql-build/mysql-${{ matrix.mysql_version.version }}/mysql/{Docs,include,lib,LICENSE,man,README,share,support-files} build-output

      - name: Extract runtime_output_directory into build output folder
        run: cp -r mysql-build/mysql-${{ matrix.mysql_version.version }}/mysql/runtime_output_directory build-output/bin

      - name: Upload build to GitHub Actions Artifacts
        uses: actions/upload-artifact@4.6.2
        with:
          name: ${{ matrix.os.arch }}-${{ matrix.mysql_version.version }}-build-output
          path: build-output
          if-no-files-found: error
          compression-level: 9

      - name: Create tar of build
        run: tar -cvzf mysql-musl-${{ matrix.mysql_version.version }}-${{ matrix.os.arch }}.tar.gz build-output

      - name: Upload tarred build output folder to GitHub Actions Artifacts
        uses: actions/upload-artifact@4.6.2
        with:
          name: ${{ matrix.os.arch }}-${{ matrix.mysql_version.version }}-build-output-tar
          path: mysql-musl-${{ matrix.mysql_version.version }}-${{ matrix.os.arch }}.tar.gz
          if-no-files-found: error
          compression-level: 0

      - name: Generate build attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: mysql-musl-${{ matrix.mysql_version.version }}-${{ matrix.os.arch }}.tar.gz

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@81c65b7cd4de9b2570615ce3aad67a41de5b1a13 #v2.11.2
        with:
          repo_token: ${{ secrets.PAT }}
          overwrite: true
          release_name: Latest Build
          file: mysql-musl-${{ matrix.mysql_version.version }}-${{ matrix.os.arch }}.tar.gz
          tag: current
          body: Latest builds of MySQL server for musl libc.

