name: Build Binaries

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.${{ matrix.os-suffix }}

    strategy:
      fail-fast: false
      matrix:
        os-suffix: ['04', 04-arm]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@4.2.2

      - name: Build Docker Image
        run: docker build -t alpine-build .

      - name: Export image contents
        run: docker export $(docker create alpine-build) -o image-output.tar.gz

      - name: Unzip image contents
        run: tar -xzvf image-output.tar.gz

      - name: Create build output folder
        run: mkdir build-output

      - name: Copy license and README into bld folder
        run: cp image-output/mysql-build/mysql-9.4.0/{LICENSE,README} image-output/mysql-build/mysql-9.4.0/bld

      - name: Extract important files and folders from bld folder into build output fgolder
        run: cp -r image-output/mysql-build/mysql-9.4.0/{bin,Docs,include,lib,LICENSE,man,README,share,support-files} build-output

      - name: Upload build to GitHub Actions Artifacts
        uses: actions/upload-artifact@4.6.2
        with:
          name: ${{ matrix.os-suffix}}-image-output
          path: build-output
          if-no-files-found: error
          compression-level: 9
