name: Build Binaries

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.${{ matrix.os-suffix }}

    strategy:
      fail-fast: false
      matrix:
        os-suffix: ['04', 04-arm]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@4.2.2

      - name: Build Docker Image
        run: docker build -t alpine-build .

      - name: Export image contents
        run: docker export $(docker create alpine-build) -o image-output.tar.gz

      - name: Upload image output to GitHub Actions Artifacts
        uses: actions/upload-artifact@4.6.2
        with:
          name: ${{ matrix.os-suffix}}-image-output
          path: image-output.tar.gz
          if-no-files-found: error
          compression-level: 9
